steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/substack-digest-05449/demo-gauntlet-frontend'
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend'
images:
  - 'gcr.io/substack-digest-05449/demo-gauntlet-frontend'
substitutions:
  _VITE_API_URL: '/' # Default value
