apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: demo-gauntlet-backend
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: localhost
        - name: PROJECT_NAME
          value: Demo Gauntlet
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: demo-gauntlet-secrets
              key: openai-api-key
        - name: BRAVE_API_KEY
          valueFrom:
            secretKeyRef:
              name: demo-gauntlet-secrets
              key: brave-api-key
        - name: BETA_INVITE_CODE
          valueFrom:
            secretKeyRef:
              name: demo-gauntlet-secrets
              key: beta-invite-code
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: demo-gauntlet-secrets
              key: secret-key
        - name: ALLOWED_ORIGINS
          value: "*"
        image: gcr.io/substack-digest-05449/demo-gauntlet-backend@sha256:2d7f6733f4dbfa04fcb542cf4a1e1564cbb3d7e7943d4545d93491fa3f86ece6
        name: backend
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "4Gi"
            cpu: "2000m"
      - image: redis:7-alpine
        name: redis
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
      - command:
        - arq
        - backend.worker.WorkerSettings
        env:
        - name: REDIS_HOST
          value: localhost
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: demo-gauntlet-secrets
              key: openai-api-key
        - name: BRAVE_API_KEY
          valueFrom:
            secretKeyRef:
              name: demo-gauntlet-secrets
              key: brave-api-key
        image: gcr.io/substack-digest-05449/demo-gauntlet-backend@sha256:2d7f6733f4dbfa04fcb542cf4a1e1564cbb3d7e7943d4545d93491fa3f86ece6
        name: worker
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
